server {
    listen 8080;
    server_name localhost;
    root /usr/share/nginx/html;
    default_type application/json;

    location = /api/health {
        default_type application/json;
        alias /usr/share/nginx/html/api/health.json;
        add_header Cache-Control "no-store";
    }

    location = /api/product {
        default_type application/json;
        alias /usr/share/nginx/html/api/product.json;
        add_header Cache-Control "no-store";
    }

    location / {
        try_files $uri $uri/ =404;
    }
}
